# Generated by Django 4.0.1 on 2022-03-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='careers_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_details', models.CharField(default='', max_length=100)),
                ('last_date', models.CharField(default='', max_length=100)),
                ('file', models.FileField(upload_to='careers/')),
            ],
        ),
        migrations.CreateModel(
            name='news_lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tender_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('last_date', models.CharField(default='', max_length=100)),
                ('file', models.FileField(upload_to='tenders/')),
            ],
        ),
    ]
