# Generated by Django 4.0.1 on 2022-03-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanveevapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers_register',
            name='last_date',
            field=models.DateField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tender_register',
            name='last_date',
            field=models.DateField(default='', max_length=100),
        ),
    ]
