# Generated by Django 4.0.1 on 2022-03-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanveevapp', '0002_alter_careers_register_last_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=100)),
                ('date', models.DateField(default='', max_length=100)),
            ],
        ),
    ]
